


export const metadata = {
    title: 'Admisi | BMN',
    description: 'Generated by create next app',
}

interface ChildNode {
    children: React.ReactNode,
    modal: React.ReactNode
}

export default function KendaraanDinasRootLayout({ children }: ChildNode) {

    // console.log("MODALLL", modal)
    return (
        <>

            <h1>Kendaraan Dinas</h1>
            {children}


        </>

    )
}
