


export const metadata = {
    title: 'Admisi | BMN',
    description: 'Generated by create next app',
}

interface ChildNode {
    children: React.ReactNode,
    modal: React.ReactNode
}

export default function KendaraanDinasLayout({ children, modal }: ChildNode) {

    // console.log("MODALLL", modal)
    return (
        <>

            {modal}

            {children}


        </>

    )
}
